# Lab 5: NumPy Exercises

### Chapter 3 — Data Science

This lab explores the fundamentals of **NumPy**, including array creation, dimensions, indexing, slicing, data types, copying and viewing arrays, reshaping, joining arrays, searching, sorting, and operations along different axes.

The goal is to understand not only how the NumPy syntax works, but also why each operation produces its result.

## Part 1 — Creating Arrays and Understanding Dimensions

The first set of exercises focuses on creating NumPy arrays and understanding how NumPy represents one-dimensional, two-dimensional, and higher-dimensional data.

### Question 1 — Creating a NumPy Array

**Explanation:** `np.array()` converts the Python list `[1, 2, 3, 4, 5]` into a one-dimensional NumPy array.

In [28]:
import numpy as np

#  1. insert the correct code for creating a numpy array

a = np.array([1, 2, 3, 4, 5]) # use np
print(a) # [1 2 3 4 5]

[1 2 3 4 5]


### Question 2 — Minimum Number of Dimensions

The `ndmin` argument tells NumPy the minimum number of dimensions the new array must have.

- `what(1)` creates a **1-D** array: `[1 2 3 4]`
- `what(2)` creates a **2-D** array: `[[1 2 3 4]]`
- `what(3)` creates a **3-D** array: `[[[1 2 3 4]]]`

The data stays the same, but NumPy adds additional axes around it. The `a.ndim` value therefore prints `1`, `2`, and `3`, respectively.

In [29]:
#  2. consider this function:

def what(n):
  a = np.array([1, 2, 3, 4], ndmin=n)
  print(a.ndim)
  return a

#     what is the difference between what(1), what(2) and what(3)

print(what(1)) # what do these print and why?
print(what(2))
print(what(3))

1
[1 2 3 4]
2
[[1 2 3 4]]
3
[[[1 2 3 4]]]


### Question 3 — Creating a 2-D Array

**Explanation:** Setting `ndmin=2` forces NumPy to create at least two dimensions, turning the original list into one row of a 2-D array.

In [30]:
#  3. insert the correct argument for creating a numpy array with 2 dimensions

a = np.array([1, 2, 3, 4], ndmin = 2)
print(a) # should print [[1 2 3 4]]

[[1 2 3 4]]


### Question 4 — Checking Array Dimensions

**Explanation:** The `.ndim` attribute returns the number of axes, or dimensions, in a NumPy array. The first array has one axis, while the nested array has two.

In [31]:
#  4. insert the correct syntax for checking the number of dimensions of a numpy array

a = np.array([1, 2, 3, 4])
print(a.ndim) # should print 1 (must refer to a)

b = np.array([[1, 2], [3, 4]])
print(b.ndim) # should print 2 (must refer to b)

1
2


## Part 2 — Indexing and Slicing

NumPy uses zero-based indexing like normal Python sequences. Slicing follows the general form `start:stop:step`, where the starting position is included and the stopping position is excluded.

### Question 5 — Accessing the First Element

**Explanation:** NumPy uses zero-based indexing, so index `0` refers to the first item in the array.

In [32]:
#  5. insert the correct syntax for printing the first item in the array:

a = np.array([1, 2, 3, 4])
print(a[0]) # should print 1 must use a

1


### Question 6 — Accessing an Element by Index

**Explanation:** The value `50` is the fifth element of the array, so its zero-based index is `4`.

In [33]:
#  6. insert the correct syntax for printing the number 50 from the array

a = np.array([10, 20, 30, 40, 50])
print(a[4]) # should print 50 must use a

50


### Question 7 — Indexing a 2-D Array

**Explanation:** In `a[1, 0]`, the first number selects the second row and the second number selects the first column, which contains `50`.

In [34]:
#  7. insert the correct syntax for printing the number 50 from the array

a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a[1,0]) # should print 50 must use a

50


### Question 8 — Negative Indexing

**Explanation:** An index of `-1` refers to the last element of an array, so `a[-1]` returns `50`.

In [35]:
#  8. use negative indexing to print the last item in the array

a = np.array([10, 20, 30, 40, 50])
print(a[-1]) # should print 50 must use a

50


### Question 9 — Basic Array Slicing

**Explanation:** `a[1:4]` starts at index `1` and stops before index `4`, producing `[15 20 25]`.

In [36]:
#  9. slice out everything from the second item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4]) # should print [15 20 25] must use a

[15 20 25]


### Question 10 — Slicing a Smaller Range

**Explanation:** `a[2:4]` includes indices `2` and `3` but excludes index `4`, producing `[20 25]`.

In [37]:
# 10.slice out everything from the third item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[2:4]) # should print [20 25] must use a

[20 25]


### Question 11 — Slicing with a Step

**Explanation:** `a[1:4:2]` starts at index `1`, stops before index `4`, and moves two positions at a time, producing `[15 25]`.

In [38]:
# 11. slice out every other item from the second item to (not including) the fifth item

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[1:4:2]) # should print [15 25] must use a

[15 25]


### Question 12 — Every Other Element

**Explanation:** `a[0::2]` starts at the beginning of the array and selects every second element, producing `[10 20 30 40]`.

In [39]:
# 12. slice out every other item from the entire array

a = np.array([10, 15, 20, 25, 30, 35, 40])
print(a[0::2]) # should print [10 20 30 40] must use a

[10 20 30 40]


## Part 3 — Data Types, Copies, and Views

NumPy arrays are homogeneous, meaning their elements share a common data type. NumPy also distinguishes between independent copies of data and views that share data with another array.

### Question 13 — Array Data Type

**Explanation:** The `.dtype` attribute reports the type used to store the array's elements. Since the array contains whole numbers, NumPy selects an integer type such as `int64` or `int32`, depending on the system.

In [40]:
# 13. insert correct syntax to print the datatype of an array

a = np.array([1, 2, 3])
print(a.dtype) # should print something indicating this is an array of integers

int64


### Question 14 — String Arrays and Type Conversion

Using `dtype='S'` stores the values as fixed-width byte strings instead of numbers.

- `a.dtype` prints a string data type such as `|S1`.
- `a[0] + a[1]` produces `b'12'` because the byte strings `b'1'` and `b'2'` are concatenated.
- `a.astype('i')` converts the string representations of the numbers into integers.
- `b[0] + b[1] + b[3]` performs numerical addition: `5 + 1 + 3 = 9`.
- `a[0] + a[1] + a[3]` performs byte-string concatenation and produces `b'513'`.

This demonstrates that the data type determines how operations such as `+` behave.

In [41]:
# 14. insert the correct argument to specify that array should be of type STRING

a = np.array([1, 2, 3, 4], dtype="S")

#     then predict and explain the output for the following expressions

print(a.dtype)
print(a[0] + a[1])
a = np.array([5, 1, -1, 3], dtype='S')
b = a.astype('i') # what happens here?
print(b[0] + b[1] + b[3])
print(a[0] + a[1] + a[3])

|S1
b'12'
9
b'513'


### Question 15 — Converting Floats to Integers

**Explanation:** `astype('i')` converts the floating-point values to integers. The decimal portions are removed, resulting in `[1 2 3]`.

In [42]:
# 15. insert correct method to change data type to integer

a = np.array([1.1, 2.1, 3.1])
b = a.astype("i")
print(b) # should print [1 2 3] now

[1 2 3]


### Question 16 — Copy vs. Assignment

`a.copy()` creates an independent copy of the original array.

Therefore, changing `x[0]` to `-5` does **not** change `a`.

However, `b = a` does not make a new array. Both variables refer to the same array object, so changing `b[0]` to `-25` also changes `a`.

Final output:

`[1 2 3 4 5]`

followed by:

`[-25 2 3 4 5]`

In [43]:
# 16. use the correct method to make a copy of the array

a = np.array([1, 2, 3, 4, 5])
x = a.copy() # must use a to make a copy of it

#     then predict the effect of the following expressions

x[0] = -5
print(a) # does a see the change?
b = a
b[0] = -25
print(a) # does a see the change?

[1 2 3 4 5]
[-25   2   3   4   5]


### Question 17 — NumPy Views and the `base` Attribute

A view shares its underlying data with another NumPy array.

- `a.base` is `None` because `a` owns its data.
- `d.base` refers to `a` because `d = a.view()` shares `a`'s data.
- `b = a` is simply another reference to the same array, so `b.base` is also `None`.
- `c = a.copy()` creates independent data, so `c.base` is `None`.

The view is different because it is a separate NumPy array object that still uses the original array's data.

In [44]:
# 17. use the correct method to make a view of this array:

a = np.array([1, 2, 3, 4, 5])
d = a.view()

#     then predict the effect of these expressions:

print(a.base)
print(d.base) # why is this different from all the others?
b = a
print(b.base)
c = a.copy()
print(c.base)

None
[1 2 3 4 5]
None
None


## Part 4 — Array Shapes, Reshaping, and Joining

The shape of an array describes how its elements are organized. NumPy can reorganize the same elements into different dimensions as long as the total number of elements stays the same.

### Question 18 — Shape and `reshape()`

The original array has four elements in one dimension, so:

`a.shape` → `(4,)`

An important detail is that `reshape()` **returns a reshaped array but does not permanently change `a` unless the result is assigned to a variable**.

Because none of the reshape results are saved, every `print(a)` still prints:

`[1 2 3 4]`

For example, `a = a.reshape(2, 2)` would be required to permanently store the new 2-D shape.

In [45]:
# 18. predict (and explain) the outcome of these expressions

a = np.array([1, 2, 3, 4])

print(a.shape)

a.reshape(1, 4)
print(a)

a.reshape(2, 2)
print(a)

a.reshape(4, 1)
print(a)

(4,)
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


### Question 19 — Reshaping a 1-D Array into 2-D Arrays

Assigning `a.reshape(2, 2)` back to `a` changes its shape to two rows and two columns:

`[[1 2]`
` [3 4]]`

For the 12-element array:

- `reshape(4, 3)` creates **4 rows and 3 columns**.
- `reshape(3, 4)` creates **3 rows and 4 columns**.

The values remain in their original order; only their organization into rows and columns changes.

In [46]:
# 19. use the correct numpy method to change the shape of an array from 1-D to 2-D:

a = np.array([1, 2, 3, 4])
a= a.reshape(2,2) # write code here must use a
print(a) # must print [[1, 2] [3 4]]

#     now predict and explain the output of these expressions

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)
b = a.reshape(3, 4)
print(b)

[[1 2]
 [3 4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Question 20 — Flattening a 2-D Array

**Explanation:** `reshape(12)` reorganizes the twelve values into a single dimension, producing:

`[1 2 3 4 5 6 7 8 9 10 11 12]`

In [47]:
# 20. use correct numpy method to change shape of an array from 2-D to 1-D

a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
b = a.reshape(12) # complete this statement to result in the output below
print(b) # must print [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Question 21 — Concatenating and Stacking Arrays

`np.concatenate((a, b))` joins the two 1-D arrays end-to-end:

`[1 2 3 4 5 6]`

For the 2-D arrays, `axis=1` tells `concatenate()` to join them by columns:

`[[1 2 5 6]`
` [3 4 7 8]]`

`np.stack((a, b), axis=0)` behaves differently because it creates a **new axis** instead of extending an existing one. The result has shape `(2, 2, 2)`:

`[[[1 2]`
`  [3 4]]`

` [[5 6]`
`  [7 8]]]`

In [48]:
# 21. use a correct numpy method to join two arrays into a single array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b)) # use np, a and b somehow
print(c) # must print [1 2 3 4 5 6]

#     then predict and explain the outcome of the following expressions

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1) # what is the effect of the second parameter?
print(c) # what gets printed and why?
c  = np.stack((a, b), axis = 0) # what does stack do differently (if anything)?
print(c) # what gets printed and why?

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Part 5 — Searching, Sorting, and Applying NumPy

The final exercises combine NumPy's searching, Boolean indexing, sorting, aggregation, and axis operations to analyze multidimensional data.

### Question 22 — Finding Matching Values

**Explanation:** `np.where(a == 4)` first creates a Boolean condition for every element and then returns the indices where that condition is true.

The value `4` occurs at indices `3`, `5`, and `6`, so the result is:

`(array([3, 5, 6]),)`

In [49]:
# 22. use correct numpy syntax to find all items with value 4

a = np.array([1, 2, 3, 4, 5, 4, 4])
where = np.where(a == 4) # complete statement, must use np, a and 4
print(where) # must print (array([3, 5, 6]),)

(array([3, 5, 6]),)


### Question 23 — Sorting an Array

**Explanation:** `np.sort(a)` returns a new array containing the elements in ascending order:

`[0 1 2 3]`

The original array is not changed unless the sorted result is assigned back to it.

In [50]:
# 23. use the correct numpy method to return a sorted array

a = np.array([3, 2, 0, 1])
b = np.sort(a) # complete statement, must use np and a
print(b) # must print [0 1 2 3]

[0 1 2 3]


### Question 24 — Exercise 3-1: Maximum After-Tax Income

First, the after-tax income is calculated element-by-element using:

`salaries - salaries * taxation`

The maximum value in the resulting matrix is `81.0`.

The expression `after_tax_income == max_income` creates a Boolean matrix that is `True` only where the maximum occurs. `np.nonzero()` finds the row containing that value, and that row index is then used to select the corresponding name.

The person with the highest after-tax income is **Tim**, with an after-tax income of **$81,000**.

In [51]:
# 24. solve exercise 3-1 on page 57

import numpy as np

# Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

names = np.array(['Alice', 'Bob', 'Tim'])

salaries = np.array([alice, bob, tim])

taxation = np.array([
    [0.2, 0.25, 0.22],
    [0.4, 0.5, 0.5],
    [0.1, 0.2, 0.1]
])

# Calculate each person's after-tax income
after_tax_income = salaries - salaries * taxation

# Find the maximum after-tax income
max_income = np.max(after_tax_income)

# Use selective indexing to find the person associated with that maximum
max_name = names[np.nonzero(after_tax_income == max_income)[0]]

print("Maximum after-tax income:", max_income)
print("Person with the maximum after-tax income:", max_name)

Maximum after-tax income: 81.0
Person with the maximum after-tax income: ['Tim']


### Question 25 — Averaging Along Different Axes

The `axis` argument determines which dimension NumPy collapses while calculating the average.

**`axis=0`**

NumPy averages corresponding positions across the two outer arrays:

`[[3. 4.]`
` [5. 6.]]`

**`axis=1`**

NumPy averages across the rows inside each outer array:

`[[2. 3.]`
` [6. 7.]]`

**`axis=2`**

NumPy averages the values inside each innermost row:

`[[1.5 3.5]`
` [5.5 7.5]]`

Changing the axis changes the direction in which the multidimensional array is collapsed.

In [52]:

# 25. predict and explain the effect of the following expressions

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.average(a, axis=0)) # review the meaning of the axis parameter
print(np.average(a, axis=1))
print(np.average(a, axis=2))

print(a)


[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Question 26 — Sorting Along Different Axes

The `axis` argument tells NumPy which dimension should be sorted.

**`axis=0`** sorts corresponding positions across the three outer 2-D arrays:

    [[[ 1  2  3]
      [ 4  5  6]
      [ 7  8  9]]

     [[11 12 10]
      [13 14 15]
      [16 17 18]]

     [[19 20 21]
      [22 23 24]
      [25 26 27]]]

**`axis=1`** sorts vertically within each 2-D array:

    [[[ 1  2  3]
      [ 7  5  6]
      [22  8  9]]

     [[ 4 12 10]
      [11 14 15]
      [16 17 18]]

     [[13 20 21]
      [19 23 24]
      [25 26 27]]]

**`axis=2`** sorts each innermost row from left to right:

    [[[ 1  2  3]
      [ 5  6 22]
      [ 7  8  9]]

     [[10 11 12]
      [ 4 14 15]
      [16 17 18]]

     [[19 20 21]
      [13 23 24]
      [25 26 27]]]

The values themselves do not move between unrelated positions; NumPy sorts only along the selected axis.

In [53]:
# 26. predict and explain the effect of the following expressions

a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

b = np.sort(a, axis=0)
print(b) # what gets printed and why?
c = np.sort(a, axis=1)
print(c)
d = np.sort(a, axis=2)
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 10]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 7  5  6]
  [22  8  9]]

 [[ 4 12 10]
  [11 14 15]
  [16 17 18]]

 [[13 20 21]
  [19 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 5  6 22]
  [ 7  8  9]]

 [[10 11 12]
  [ 4 14 15]
  [16 17 18]]

 [[19 20 21]
  [13 23 24]
  [25 26 27]]]
